spring.application.name=Shopping_Mall_Management
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_mall_project
spring.datasource.username=postgres
spring.datasource.password=60451472

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true